bool only_color_and_geometry
jsk_recognition_msgs/ClusterPointIndices cluster
sensor_msgs/PointCloud2 cloud
sensor_msgs/Image image
jsk_recognition_msgs/BoundingBoxArray instance_boxes
jsk_recognition_msgs/BoundingBoxArray cluster_boxes
---
bool success
uint32[] labels
neatness_estimator_msgs/Features features

